# Site settings
title: Doruu's garage 
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
copyright_name: Doruu's garage 
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://doruu.github.io"
#twitter_username: SBootstrap
github_username: doruu 
#facebook_username:  IronSummitMedia
email_username: doruu.lee@gmail.com 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
disqus: doruu

theme: jekyll-theme-slate